services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: restaurante
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      app_net:
        ipv4_address: 172.16.15.10
  orders_service:
    build: ./backends/orders
    container_name: orders_service
    restart: always
    expose:
      - "5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: restaurante
      DB_USER: admin
      DB_PASSWORD: admin123
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.15.20

  cocina_cli:
    build: ./cli/cocina
    container_name: cocina_cli
    stdin_open: true
    tty: true
    environment:
      ORDERS_URL: http://api_gateway/orders
      LDAP_HOST: ldap://openldap
      LDAP_BASE: dc=restaurante,dc=local
    networks:
      client_net:

  cajero_cli:
    build: ./cli/cajero
    container_name: cajero_cli
    stdin_open: true
    tty: true
    environment:
      ORDERS_URL: http://api_gateway/orders
      LDAP_HOST: openldap
      LDAP_PORT: 389
      LDAP_BASE: dc=restaurante,dc=local
    depends_on:
      - nginx
      - openldap
    networks:
      client_net:

  nginx:
    image: nginx:alpine
    container_name: api_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - orders_service
      - deliveries_service
    networks:
      app_net:
        ipv4_address: 172.16.15.5
      client_net:
        ipv4_address: 172.16.16.5

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ADMIN_PASSWORD: adminldap
      LDAP_DOMAIN: restaurante.local
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
      LDAP_TLS: "false"
    ports:
      - "389:389"
    volumes:
      - ./ldap/bootstrap/ldif/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    networks:
      - client_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: 172.16.15.11

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.15.0/24

  client_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.16.0/24

volumes:
  postgres_data:
  ldap_data:
  ldap_config: