version: "3.9"

services:
  orders:
    build: ./backends/orders
    container_name: orders_service
    ports:
      - "5000:5000"
    volumes:
      - ./db:/app/db

  deliveries:
    build: ./backends/deliveries
    container_name: deliveries_service
    ports:
      - "5001:5001"
    volumes:
      - ./db:/app/db

  nginx:
    image: nginx:alpine
    container_name: api_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - orders
      - deliveries
