
services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: restaurante
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - restaurante_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  orders_service:
    build: ./backends/orders
    container_name: orders_service
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./db:/app/db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=restaurante
      - DB_USER=admin
      - DB_PASSWORD=admin123
    depends_on:
      db:
        condition: service_healthy
    networks:
      - restaurante_net

  deliveries_service:
    build: ./backends/deliveries
    container_name: deliveries_service
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./db:/app/db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=restaurante
      - DB_USER=admin
      - DB_PASSWORD=admin123
    depends_on:
      db:
        condition: service_healthy
    networks:
      - restaurante_net

  nginx:
    image: nginx:alpine
    container_name: api_gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      orders_service:
        condition: service_started
      deliveries_service:
        condition: service_started
    networks:
      - restaurante_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - restaurante_net

volumes:
  postgres_data:

networks:
  restaurante_net:
    driver: bridge
